### ISSUE TITLE
Typo

### ISSUE THREAD

**Issue by MostafaKhezri** [DanielSank/DanielSank.github.io#2]
[Technical reading](https://github.com/DanielSank/DanielSank.github.io/blob/master/_posts/2016-09-17-technical_reading_list.md) post, Quantum mechanics section, Sakurai, last point: "lift the degeneracy"

P.S. Github renders all the .md files and you can't get a look at the code like other files on github. I can't open the post in a view that gives me access to code line with line number, and this is why I had to address the issue like this.

**Comment by DanielSank** [comment]
You actually can access the md source. When you click the link to go to that file, there's a "raw" button.
