### ISSUE TITLE
Installing virtualenv

### ISSUE THREAD

**Issue by lovesegfault** [DanielSank/DanielSank.github.io#3]
Recently you've linked me your [write up](https://docs.google.com/document/d/1hXM_noMrsp1LTic_jSbgHHr5a2rwmI3b7DZdoo9IYGo/edit#heading=h.nti51vo0bfnn) on setting up `virtualenv`, and I thought it was super useful.

Could you consider making it into a blog post?

**Comment by DanielSank** [comment]
Any particular reason to make this a blog post, given that there's already the Google Drive doc?

**Comment by lovesegfault** [comment]
Visibility. You need to share your google doc link to people, anyone can find it on your blog. Also, it's useful material that could give it usability and increase it's footprint on search engines.

**Comment by DanielSank** [comment]
So should I just make a blog post with useful links? Note that google docs can be made publicly searchable on the web...

**Comment by lovesegfault** [comment]
Perhaps, I still think a proper blog post is better though, although it's up to you I guess.

**Comment by DanielSank** [comment]
Well yes it's up to me, but I'm trying to understand what's the best way to stay DRY and still get good exposure. I guess I could write a blog post explaining the ideas and point to the drive doc for details.
